# Generated by Django 5.1.6 on 2025-03-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='status',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('completed', 'Completed')], default='in-progress', max_length=20),
        ),
        migrations.AddField(
            model_name='app',
            name='task_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='app',
            name='task',
            field=models.CharField(max_length=50),
        ),
    ]
